# Generated by Django 4.1.7 on 2023-07-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_code_exam_codequestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeQuestions',
            new_name='code_question',
        ),
    ]
